name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use.
        
    - working-directory: ./WebApplication3
      run: dotnet build --configuration Release

    - working-directory: ./WebApplication3
      name: dotnet publish
      run: |
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/webapi3 
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        docker build -f ./WebApplication3/Dockerfile -t ${{ secrets.ACR_ENDPOINT }}/webapi3:main .
        docker push ${{ secrets.ACR_ENDPOINT }}/webapi3:main
#       docker build -f ./WebApplication3/Dockerfile -t ${{ secrets.ACR_ENDPOINT }}/webapi3:${{ github.sha }} .
#       docker push ${{ secrets.ACR_ENDPOINT }}/webapi3:${{ github.sha }} 
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'd231657'
        publish-profile: ${{ secrets.D231657_PUBLISH_PROFILE }}
        images: '${{ secrets.ACR_ENDPOINT }}/webapi3:main'
